Making CLI components wrappers more robust

diff --git a/services_setup/flink-cli/flink_wrappers/flink b/services_setup/flink-cli/flink_wrappers/flink
--- a/services_setup/flink-cli/flink_wrappers/flink
+++ b/services_setup/flink-cli/flink_wrappers/flink
@@ -61,33 +61,37 @@ if [[ -d $last_param ]]; then
     export FILENAME_ARG=""
 else
     if [[ -f $last_param ]]; then
-        export LAST_ARG_DIR=`dirname $last_param`
+        export LAST_ARG_DIR=$(dirname $last_param)
 
         # manipulating file path
-        export FILENAME_ARG=`realpath $last_param`
-        export LAST_ARG_DIR=`realpath $LAST_ARG_DIR`
+        export FILENAME_ARG=$(realpath $last_param)
+        export LAST_ARG_DIR=$(realpath $LAST_ARG_DIR)
         set -- "${@:1:$(($#-1))}"
     fi
 fi
 
 if [[ "$LAST_ARG_DIR" != "" ]]; then
-    if [[ `echo $DOCKER_VOLUMES_ARGS | grep "$LAST_ARG_DIR:$LAST_ARG_DIR:slave"` == "" ]]; then
+    if [[ $(echo $DOCKER_VOLUMES_ARGS | grep "$LAST_ARG_DIR:$LAST_ARG_DIR:slave") == "" ]]; then
         export DOCKER_VOLUMES_ARGS=" -v $LAST_ARG_DIR:$LAST_ARG_DIR:slave $DOCKER_VOLUMES_ARGS"
     fi
 fi
 
 # Add standard folders if not already part of it
 # (avoid /var/lib/flink which is used inside container for gluster mounts)
-if [[ `echo $DOCKER_VOLUMES_ARGS | grep /var/log/flink` == "" ]]; then
+if [[ $(echo $DOCKER_VOLUMES_ARGS | grep /var/log/flink) == "" ]]; then
     export DOCKER_VOLUMES_ARGS=" -v /var/log/flink:/var/log/flink:shared $DOCKER_VOLUMES_ARGS"
 fi
 
 #echo $DOCKER_VOLUMES_ARGS
 
-KUBE_SERVICES_HOSTS_FILE=`create_kube_services_hosts_file`
-if [[ ! -f $KUBE_SERVICES_HOSTS_FILE ]]; then
-    echo "Fail to create 'Kube services host file' with create_kube_services_hosts_file"
+KUBE_SERVICES_HOSTS_FILE=$(create_kube_services_hosts_file)
+if [[ $? != 0 ]]; then
+    echo "Failed to list kube services and create host file"
     exit 1
+fi
+if [[ ! -f $KUBE_SERVICES_HOSTS_FILE ]]; then
+    echo "Failed to create 'Kube services host file' with create_kube_services_hosts_file"
+    exit 2
 fi
 
 tty -s && USE_TTY="-t"
diff --git a/services_setup/spark-cli/spark_wrappers/pyspark b/services_setup/spark-cli/spark_wrappers/pyspark
--- a/services_setup/spark-cli/spark_wrappers/pyspark
+++ b/services_setup/spark-cli/spark_wrappers/pyspark
@@ -60,16 +60,20 @@ parse_cli_docker_volume_mounts \
         "$@"
 
 # Add standard folders if not already part of it
-if [[ `echo $DOCKER_VOLUMES_ARGS | grep /var/log/spark` == "" ]]; then
+if [[ $(echo $DOCKER_VOLUMES_ARGS | grep /var/log/spark) == "" ]]; then
     export DOCKER_VOLUMES_ARGS=" -v /var/log/spark:/var/log/spark:shared $DOCKER_VOLUMES_ARGS"
 fi
 
 #echo $DOCKER_VOLUMES_ARGS
 
-KUBE_SERVICES_HOSTS_FILE=`create_kube_services_hosts_file`
-if [[ ! -f $KUBE_SERVICES_HOSTS_FILE ]]; then
-    echo "Fail to create 'Kube services host file' with create_kube_services_hosts_file"
+KUBE_SERVICES_HOSTS_FILE=$(create_kube_services_hosts_file)
+if [[ $? != 0 ]]; then
+    echo "Failed to list kube services and create host file"
     exit 1
+fi
+if [[ ! -f $KUBE_SERVICES_HOSTS_FILE ]]; then
+    echo "Failed to create 'Kube services host file' with create_kube_services_hosts_file"
+    exit 2
 fi
 
 # Finding out if we have y TTY here
