git rid of DNS mess in kube infrastucture, using a simpler workaround for cli packages

diff --git a/services_setup/flink-cli/flink_wrappers/flink b/services_setup/flink-cli/flink_wrappers/flink
--- a/services_setup/flink-cli/flink_wrappers/flink
+++ b/services_setup/flink-cli/flink_wrappers/flink
@@ -89,6 +89,14 @@ fi
 
 #echo $DOCKER_VOLUMES_ARGS
 
+. /usr/local/sbin/eskimo-utils.sh
+
+KUBE_SERVICES_HOSTS_FILE=`create_kube_services_hosts_file`
+if [[ ! -f $KUBE_SERVICES_HOSTS_FILE ]]; then
+    echo "Fail to create 'Kube services host file' with create_kube_services_hosts_file"
+    exit 1
+fi
+
 /usr/bin/docker run \
         -it \
         --rm \
@@ -100,9 +108,13 @@ fi
         --mount type=bind,source=/etc/eskimo_services-settings.json,target=/etc/eskimo_services-settings.json \
         --mount type=bind,source=/home/flink/.kube/config,target=/home/flink/.kube/config \
         --mount type=bind,source=/usr/local/bin/kubectl,target=/usr/local/bin/kubectl \
+        --mount type=bind,source=$KUBE_SERVICES_HOSTS_FILE,target=$KUBE_SERVICES_HOSTS_FILE \
         -v /etc/k8s:/etc/k8s:ro \
         -e NODE_NAME=$HOSTNAME \
+        -e ADDITONAL_HOSTS_FILE=$KUBE_SERVICES_HOSTS_FILE \
         kubernetes.registry:5000/flink \
-        /usr/local/bin/flink "$@" $FILENAME_ARG
+            /usr/local/bin/kube_do /usr/local/bin/flink "$@" $FILENAME_ARG
+
+rm -Rf $KUBE_SERVICES_HOSTS_FILE
 
 # -p 5000-5010:5000-5010 \
diff --git a/services_setup/logstash-cli/logstash_wrappers/logstash b/services_setup/logstash-cli/logstash_wrappers/logstash
--- a/services_setup/logstash-cli/logstash_wrappers/logstash
+++ b/services_setup/logstash-cli/logstash_wrappers/logstash
@@ -66,6 +66,14 @@ fi
 
 #echo $DOCKER_VOLUMES_ARGS
 
+. /usr/local/sbin/eskimo-utils.sh
+
+KUBE_SERVICES_HOSTS_FILE=`create_kube_services_hosts_file`
+if [[ ! -f $KUBE_SERVICES_HOSTS_FILE ]]; then
+    echo "Fail to create 'Kube services host file' with create_kube_services_hosts_file"
+    exit 1
+fi
+
 # Don't pass -t or docker won't let us pipe input
 /usr/bin/docker run \
         -i \
@@ -75,6 +83,10 @@ fi
         $DOCKER_VOLUMES_ARGS \
         --mount type=bind,source=/etc/eskimo_topology.sh,target=/etc/eskimo_topology.sh \
         --mount type=bind,source=/etc/eskimo_services-settings.json,target=/etc/eskimo_services-settings.json \
+        --mount type=bind,source=$KUBE_SERVICES_HOSTS_FILE,target=$KUBE_SERVICES_HOSTS_FILE \
         -e NODE_NAME=$HOSTNAME \
+        -e ADDITONAL_HOSTS_FILE=$KUBE_SERVICES_HOSTS_FILE \
         kubernetes.registry:5000/logstash \
-        /usr/local/bin/logstash "$@"
+            /usr/local/bin/kube_do /usr/local/bin/logstash "$@"
+
+rm -Rf $KUBE_SERVICES_HOSTS_FILE
diff --git a/services_setup/spark-cli/spark_wrappers/spark-sql b/services_setup/spark-cli/spark_wrappers/spark-sql
--- a/services_setup/spark-cli/spark_wrappers/spark-sql
+++ b/services_setup/spark-cli/spark_wrappers/spark-sql
@@ -111,6 +111,14 @@ fi
 # Find external IP for libprocess (mesos) configuration
 . /etc/eskimo_topology.sh
 
+. /usr/local/sbin/eskimo-utils.sh
+
+KUBE_SERVICES_HOSTS_FILE=`create_kube_services_hosts_file`
+if [[ ! -f $KUBE_SERVICES_HOSTS_FILE ]]; then
+    echo "Fail to create 'Kube services host file' with create_kube_services_hosts_file"
+    exit 1
+fi
+
 /usr/bin/docker run \
         -it \
         --rm \
@@ -122,9 +130,13 @@ fi
         --mount type=bind,source=/etc/eskimo_topology.sh,target=/etc/eskimo_topology.sh \
         --mount type=bind,source=/etc/eskimo_services-settings.json,target=/etc/eskimo_services-settings.json \
         --mount type=bind,source=/home/spark/.kube/config,target=/home/spark/.kube/config \
+        --mount type=bind,source=$KUBE_SERVICES_HOSTS_FILE,target=$KUBE_SERVICES_HOSTS_FILE \
         -v /etc/k8s:/etc/k8s:ro \
         -e NODE_NAME=$HOSTNAME \
+        -e ADDITONAL_HOSTS_FILE=$KUBE_SERVICES_HOSTS_FILE \
         kubernetes.registry:5000/spark \
-        /usr/local/bin/spark-sql "$@"
+            /usr/local/bin/kube_do /usr/local/bin/spark-sql "$@"
+
+rm -Rf $KUBE_SERVICES_HOSTS_FILE
 
 # -p 5000-5010:5000-5010 \
diff --git a/services_setup/spark-cli/spark_wrappers/spark-submit b/services_setup/spark-cli/spark_wrappers/spark-submit
--- a/services_setup/spark-cli/spark_wrappers/spark-submit
+++ b/services_setup/spark-cli/spark_wrappers/spark-submit
@@ -136,6 +136,14 @@ fi
 
 export eskimo_user=`cat /etc/eskimo_user`
 
+. /usr/local/sbin/eskimo-utils.sh
+
+KUBE_SERVICES_HOSTS_FILE=`create_kube_services_hosts_file`
+if [[ ! -f $KUBE_SERVICES_HOSTS_FILE ]]; then
+    echo "Fail to create 'Kube services host file' with create_kube_services_hosts_file"
+    exit 1
+fi
+
 echo " - Calling spark-submit with arguments" "$@" "$FILENAME_ARG"
 /usr/bin/docker run \
         -it \
@@ -148,9 +156,13 @@ echo " - Calling spark-submit with arguments" "$@" "$FILENAME_ARG"
         --mount type=bind,source=/etc/eskimo_topology.sh,target=/etc/eskimo_topology.sh \
         --mount type=bind,source=/etc/eskimo_services-settings.json,target=/etc/eskimo_services-settings.json \
         --mount type=bind,source=/home/spark/.kube/config,target=/home/spark/.kube/config \
+        --mount type=bind,source=$KUBE_SERVICES_HOSTS_FILE,target=$KUBE_SERVICES_HOSTS_FILE \
         -v /etc/k8s:/etc/k8s:ro \
         -e NODE_NAME=$HOSTNAME \
+        -e ADDITONAL_HOSTS_FILE=$KUBE_SERVICES_HOSTS_FILE \
         kubernetes.registry:5000/spark \
-        /usr/local/bin/spark-submit "$@" $FILENAME_ARG
+            /usr/local/bin/kube_do /usr/local/bin/spark-submit "$@" $FILENAME_ARG
+
+rm -Rf $KUBE_SERVICES_HOSTS_FILE
 
 # -p 5000-5010:5000-5010 \
