Rationalized quite a lot of code

diff --git a/services_setup/base-eskimo/eskimo-kubectl b/services_setup/base-eskimo/eskimo-kubectl
--- a/services_setup/base-eskimo/eskimo-kubectl
+++ b/services_setup/base-eskimo/eskimo-kubectl
@@ -37,9 +37,11 @@
 echo_usage() {
     echo "eskimo-kubectl COMMAND SERVICE NODE"
     echo "where "
-    echo "    COMMAND in [logs, start, stop, restart, uninstall]"
-    echo "    SERVICE is the target eskimo kubernetes service"
-    echo "    NODE the target node whwre the service is expected to run (to distinguish multiple instances services)"
+    echo "    COMMAND in [logs, start, stop, restart, uninstall, delete_node]"
+    echo "    SERVICE is the target eskimo kubernetes service "
+    echo "            (pass NULL for commands not requiring service)"
+    echo "    NODE the target node where the service is expected to run "
+    echo "         (to distinguish multiple instances services, pass NULL when not required)"
 }
 
 if [[ $1 == "-h" ]]; then
@@ -374,6 +376,34 @@ function start_service() {
     . $SERVICE_FILE | call-kubectl apply -f -
 }
 
+function delete_node() {
+
+    if [[ "$1" == "" ]]; then
+        echo "delete_node takes node as first argument"
+        exit 1
+    fi
+    local NODE=$1
+
+    echo " - Deleting node $NODE"
+
+    echo "   + cordon node"
+    kubectl cordon $NODE
+
+    echo "   + Delete / force delete all pods from node"
+    for pod in $(kubectl get pods -o wide | grep $NODE | cut -d ' ' -f 1); do
+        kubectl delete pod $pod --wait=true --timeout=30s --now=true
+        if [[ $? == 0 ]]; then
+            kubectl delete pod $pod --wait=false --force=true
+        fi
+    done
+
+    echo "   + drain node"
+    kubectl drain $NODE --delete-local-data --force --timeout=120s
+
+    echo "   + delete node"
+    kubectl delete node $NODE
+}
+
 
 if [[ "$COMMAND" == "logs" ]]; then
     show_log $SERVICE $NODE
@@ -389,6 +419,9 @@ elif [[ "$COMMAND" == "stop" ]]; then
 
 elif [[ "$COMMAND" == "uninstall" ]]; then
     uninstall_service $SERVICE
+
+elif [[ "$COMMAND" == "delete_node" ]]; then
+    delete_node $NODE
 
 else
     echo "Unknown Command : $COMMAND"
